[package]
name = "wasm_rust_ray_tracing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
result = "1.0.0"
rand = "0.8.5"
rayon = "1.5"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
rust_ray_tracing = { path = "../rust_ray_tracing" }